server:
  port: 8112
spring:
  application:
    name: admin-server
  security:
    user:
      name: yangming
      password: 123456
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://yangming:123456@localhost:8100/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}