server:
  port: 8110
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://yangming:123456@localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  #忽略默认的路由配置
  ignored-services: user-service,feign-service
  #可以配置前缀
  #prefix:/zuul-proxy

#配置路由端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
#默认路由配置规则
#zuul:
#  routes: #给服务配置路由
#    user-service:
#      path: /user-service/**
#    feign-service:
#      path: /feign-service/**
