server:
  port: 8102
spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://yangming:123456@localhost:8100/eureka/
    registry-fetch-interval-seconds: 5
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: localhost
    metadata-map:
      zone: jiangsu
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}