server:
  port: 8113
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8112
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://yangming:123456@localhost:8100/eureka/
    registry-fetch-interval-seconds: 5
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: jiangsu
    prefer-ip-address: false